on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        head: master
        extra_args: --results=verified,unknown
